services:
  sniproxy:
    image: sni-ssl-proxy:latest
    container_name: sniproxy
    hostname: sniproxy
    expose:
      - 80
      - 443
      - 993
      - 996
      - 465
      - 587
    environment:
      - BIND_ADDRESS=0.0.0.0
      - WORKERS_NO=1
      - USE_TOR=yes
#      - UPSTREAM_SOCKS=IP:PORT
    restart: unless-stopped